### ISSUE TITLE
Licensing problems

### ISSUE THREAD

**Issue by Szumo** [geekpradd/PyLyrics#1]
Hi,

This library is screen-scraping Wikia's pago to get the lyrics, and according to http://lyrics.wikia.com/LyricWiki:Permission :
"""
"Screen-scraping" the HTML of the song pages to just display the lyrics is not a licensed use of the site. If you are screen-scraping we highly recommend that you seek out a source of licensing on your own (sorry, we are not approved to sell this) to avoid legal problems. 
"""

Users of your library will be breaking copyrights on lyrics, unless they have a separate license.

**Comment by geekpradd** [comment]
So how do we get this separate license? In that case using the lyrics.wikia API (which sucks) should cause problems too right?

**Comment by geekpradd** [comment]
And aren't the lyrics community generated like Wikipedia? Wikipedia has a very liberal license and the same should be the case with wikia.

I'll have to contact Jimmy Wales on Quora about this.

Thanks for letting me know.
